config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: redirect('/dashboard')
 
  get 'dashboard', to: 'dashboard#index', as:'dashboard'
  get 'account' , to:'dashboard#account', as: 'account'
  get 'editpay' , to:'dashboard#editpay', as: 'editpay'
  get 'offer', to: 'dashboard#offer', as:'offer'
  get 'books', to:'books#productlisting', as:'books'
  get 'orderpay', to:'books#orderpay', as:'orderpay'
  get 'books/:id', to: 'books#productdetails', as: 'productdetails_book'
  get 'books/:id', to: 'books#productdetails', as: 'book'
  get 'myorder/:id', to:'books#myorder', as: 'myorder' 
  get 'quiz',to: 'contest#quiz', as:'quiz'
  get 'productdetails', to: 'books#productdetails', as: 'productdetails'
  get 'review/:id', to: 'books#review', as: 'review'
  post 'books', to: 'books#create'
  get 'reviewresult', to: 'books#reviewresult', as: 'reviewresult'

  get 'books/new', to: 'books#new', as: 'newbook'
  get 'books', to: 'books#booksearch', as: 'booksearch'
  get 'books/:id', to: 'books#show', as: 'order'
  
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index   
        render :index
    end
    
    def account
        render :account
    end

    def editpay
        @payment = Payment.all
        render :editpay
    end
    

    def offer   
        render :offer
    end
end
   

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/account.html.erb
<p>
 <% if user_signed_in? %>
 <h1>Account page</h1>

<h4>Profile Details<h4>

Name:
<%= "#{current_user.name}" %>
</p>
<p>
phone number:
<%= "#{current_user.phoneno}" %>
</p>
<p>
email:
<%= "#{current_user.email}" %>
</p>

<p>
address:
<%= "#{current_user.address}" %>
</p>

 
    <% end %>

<% if user_signed_in? %>
<%= link_to 'Payment information',editpay_path, class:'btn btn-primary' %>

<% else %>
<h3> Requried Sign in </h3><br>

 <%= link_to 'Sign In', new_user_session_path, class:'me-md-2' %>
 <%= link_to 'Sign Up', new_user_registration_path %>
 <% end %>

app/views/dashboard/editpay.html.erb
 <h4 class="mb-3">Payment</h4>

          <div class="my-3">
            <div class="form-check">
              <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required>
              <label class="form-check-label" for="credit">Credit card</label>
            </div>
            <div class="form-check">
              <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="debit">Debit card</label>
            </div>
            <div class="form-check">
              <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="paypal">PayPal</label>
            </div>
          </div>

          <form class="was-validated">
  <div class="col-md-6">
    <label for="validationTextarea">Name on Credit card</label>
    <textarea class="form-control is-invalid" id="validationTextarea" placeholder="Please enter your name " required></textarea>
    <div class="invalid-feedback">
    </div>
  </div>
 <div class="col-md-6">
              <label for="cc-number" class="form-label" name='creditcradnum'>Credit card number</label>
              <input type="number" class="form-control is-inivalid" id="cc-number" placeholder="" required>
              <div class="invalid-feedback">
               
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-expiration" class="form-label">CVV</label>
              <input type="number" class="form-control is-invalid" id="cc-expiration" placeholder="" required>
              <div class="invalid-feedback">
                
              </div>
              
            <div class="col-md-12">
              <label for="cc-expiration" class="form-label">exp date</label>
              <input type="date" class="form-control is-invalid" id="cc-expiration" placeholder="" required>
              <div class="invalid-feedback">
                
              </div>
	 </div>
 <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
        </form>
      </div>
    </div>
  </main>

app/views/dashboard/index.html.erb
<style>
h1{
    font-family: monospace;

} 

</style>


   <div>
      <h1>Comic Trekker</h1> 
      
      
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      
      <% if user_signed_in? %>
          <%= link_to "Hi, #{current_user.name}", edit_user_registration_path %>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to 'Sign In', new_user_session_path, class:'me-md-2' %>
            <%= link_to 'Sign Up', new_user_registration_path %>
        <% end %>
      </div>
      
 <% if user_signed_in? %>
     <h3> <div class="top">my favourite Character: <%= "#{current_user.favch}" %> <%= link_to 'Claim your exiting offer', offer_path(@dashboard), class: 'btn btn-primary' %> </div>
     </h3>
            <% end %>
<div>
     <p>
     <table>
     <tr>
     <td><%= link_to 'Home', dashboard_path(@dashboard), class: 'btn btn-primary' %> </td>
      <td>&nbsp;&nbsp;&nbsp;</td>
    <td><%= link_to 'Comics', books_path(@book), class: 'btn btn-primary' %> </td>
      <td> &nbsp;&nbsp;&nbsp;    </td>
    <td><%= link_to 'Account' ,account_path(@dashboard), class: 'btn btn-primary' %></td>
      <td>  &nbsp;&nbsp;&nbsp;   </td>   
    <td><%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary' %></td>
    </td></tr>
  </table>

</p>   


      <table>
      <thead><h3>latest comic books</h3></thead>  
<tbody>
<tr>
<td>
<figure class="figure">
  <%= image_tag 'book2', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<td>
<figure class="figure">
  <%= image_tag 'book1', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<td>
<figure class="figure">
  <%= image_tag 'book2', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<td>
<figure class="figure">
  <%= image_tag 'image 6', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>

<td>
<figure class="figure">
  <%= image_tag 'image 5', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<td>
<figure class="figure">
  <%= image_tag 'image 4', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
</tr>

<tr>
<td>
<figure class="figure">
  <%= image_tag 'image 2', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<td>
<figure class="figure">
  <%= image_tag 'image3', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<td>
<figure class="figure">
  <%= image_tag 'image1', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>

<td>
<figure class="figure">
  <%= image_tag 'image3', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<td>
<figure class="figure">
  <%= image_tag 'image 2', style: 'max-width: 10rem;' %>
  <figcaption class="figure-caption text-right">Buy      14.99</figcaption>
</figure>
</td>

<td>
<%= link_to 'See All', books_path(@book)  %> 
</td>
</tr>

</tbody>
</table>

app/views/dashboard/offer.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial;
}

h3,h1,h2{
    font-family: monospace;

}

.coupon {
  border: 5px dotted #bbb;
  width: 80%;
  border-radius: 15px;
  margin: 0 auto;
  max-width: 600px;
}

.container {
  padding: 2px 16px;
  background-color: #f1f1f1;
}

.promo {
  background: #ccc;
  padding: 3px;
}

.expire {
  color: red;
}
</style>
</head>
<body>

<div class="coupon">
  <div class="container">
    <h1>Comic Trekker</h1><br>
    <center><h4>! ! ! secial coupon! ! !</h4></center>
  </div>
 <center> <%= image_tag 'coupon', style: 'max-width: 10rem;' %> </center>
  <div class="container" style="background-color:white">
  <center>  <h2><b>10$ OFF YOUR PURCHASE</b></h2></center>
  <center>  <h3> On <%= "#{current_user.favch}"  %> Character Book </h3> </center>
    <p>Have a discount coupon to use on an eligible online order? Enter the coupon code on the very last page of the checkout process, just before clicking the submit button. You'll see a text box labeled Coupon Code. Enter the code and click "Apply Coupon". </p></div>
  <div class="container">
    <p>Use Promo Code: <span class="promo">BOH232</span></p>
    <p class="expire">Expires: Jan 03, 2023</p>
  </div>
</div>

</body>
</html> 