config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: redirect('/dashboard')
 
  get 'dashboard', to: 'dashboard#index', as:'dashboard'
  get 'account' , to:'dashboard#account', as: 'account'
  get 'editpay' , to:'dashboard#editpay', as: 'editpay'
  get 'offer', to: 'dashboard#offer', as:'offer'
  get 'books', to:'books#productlisting', as:'books'
  get 'orderpay', to:'books#orderpay', as:'orderpay'
  get 'books/:id', to: 'books#productdetails', as: 'productdetails_book'
  get 'books/:id', to: 'books#productdetails', as: 'book'
  get 'myorder/:id', to:'books#myorder', as: 'myorder' 
  get 'quiz',to: 'contest#quiz', as:'quiz'
  get 'productdetails', to: 'books#productdetails', as: 'productdetails'
  get 'review/:id', to: 'books#review', as: 'review'
  post 'books', to: 'books#create'
  get 'reviewresult', to: 'books#reviewresult', as: 'reviewresult'

  get 'books/new', to: 'books#new', as: 'newbook'
  get 'books', to: 'books#booksearch', as: 'booksearch'
  get 'books/:id', to: 'books#show', as: 'order'
  
  

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id           :bigint           not null, primary key
#  book_author  :string
#  book_char    :string
#  book_price   :decimal(, )
#  book_title   :string
#  date         :string
#  description  :string
#  release_date :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  book_id      :string
#
class Book < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def productlisting
        @books = Book.all
        render :productlisting
    end


    def booksearch
        @books = Book.all
        @books = if params[:search].present?
            filter_books = books
            filter_books = books.where(book_char: params[:search][:book_char]) if params[:search][:book_char].present?
        end

        render :booksearch
    end


    def productdetails
        @book = Book.find(params[:id])
        render :productdetails
    end

    def myorder
        @book = Book.all
        @book = Book.find(params[:id])
        render :myorder
    end


	def orderpay
        render :orderpay
    end

	def reviewresukt
        @book = Book.all
        render :reviewresult
    end

    def myorder
        @book = Book.find(params[:id])
        @order= Order.find(params[:id])
        render :myorder
    end
    

    def create
        @book = Book.productdetails(params.require(:book).permit(:review))
        if @book.save
            flash[:success] = 'New review added successfully!'
            redirect_to review_url
          else
            flash.now[:error] = 'To-do item creation failed'
            render :new, status: :unprocessable_entity
          end
    end

    
    def productdetails
        @book = Book.find(params[:id])
        render :productdetails
    end



    def index
		if params[:category].blank?
			@books = Book.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		if @book.reviews.blank?
			@average_review = 0
		else
			@average_review = @book.reviews.average(:rating).round(2)
		end
	end

	def new
		@book = current_user.books.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]

		if @book.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@book.category_id = params[:category_id]
		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path
	end

	private

		def book_params
			params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
		end

		def find_book
			@book = Book.find(params[:id])
		end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for :filter, url: booksearch_path, method: :get do |f| %>
    <ul>
  
    
    <li>
    <div class="col-md-3">
      <label>Book Character</label>
      <%= f.input :book_char, collection: Book.all, input_html: { class: "form-control" }, include_blank: "Select a character", label: false %>
    </div>
    </li>
  </div>
  <li>
  <div class="mt-2">
    <%= f.submit "Search", class: "btn btn-sm btn-primary" %>
  </div>
  </li>
  </ul>

<% end %>

app/views/books/_reviewform.html.erb
<%= simple_form_for @review, url:  productdetails_path, html: { "data-turbo": false, class: "row g-3" } do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this user review from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-12 mt-3">

    <label class="form-label">Review</label>
    <%= f.input :book_id, as: :hidden, input_html: { value: @book_id } %>
    <%= f.input :review, input_html: { class: "form-control" }, label: false %>
  </div>
  <div class="col-12">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/mycart.html.erb
<html>
<head>
<title>Instructor Evaluation</title>
<style>
.button {
display: block;
margin-top: 10px;
}
</style>
</head>
<body>
<form  id="form1">
<p>The instructor was prepared for class.</p>
<input type="radio" name="prepared" value="1" /><label for="prepared_one">1</label>
<input type="radio" name="prepared" value="2" /><label for="prepared_two">2</label>
<input type="radio" name="prepared" value="3" /><label for="prepared_three">3</label>
<input type="radio" name="prepared" value="4" /><label for="prepared_four">4</label>
<input type="radio" name="prepared" value="5" /><label for="prepared_five">5</label>

<p>The topic was interesting to me.</p>
<input type="radio" name="interesting" value="1" /><label for="int_one">1</label>
<input type="radio" name="interesting" value="2" /><label for="int_two">2</label>
<input type="radio" name="interesting" value="3" /><label for="int_three">3</label>
<input type="radio" name="interesting" value="4" /><label for="int_four">4</label>
<input type="radio" name="interesting" value="5" /><label for="int_five">5</label>


<button type="submit" value="Submit" class="button">Submit</button>
</form>

<p>Question 1 Answer: <span id="quest1"></span></p>
<p>Question 2 Answer: <span id="quest2"></span></p>
<p>Score Total: <span id="total"></span></p>
<p>Score Average: <span id="average"></span></p>
    <p>Average above 3 (Yes or No): <span id="above3"></span></p>
    <p>Which measures scored 5?: <span id="score5"></span></p>

<script>
//this is the generic function that submits the form. Name of form above must be the same as id below
document.getElementById("form1").onsubmit=function() {

//code the rest of your script here




return false; // required to not refresh the page; just leave this here
}
</script>

</body>
</html>

app/views/books/myorder.html.erb
<h1>My Orders</h1>

<%= image_tag 'book2.jpg', class: 'w-80', style: 'max-width: 10rem;' %>
<p>
    <%= @book.book_id %>
</p>
<p>
<%= @book.book_title %>
</p>

<p>
    <%= @book.book_price %>
</p>

<p>
<%= @order.order_date %>
</p>

<%= link_to 'Confirm Order', orderpay_path(@book), class: 'btn btn-primary' %>


app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">

		<h1>New Book</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/books/orderpay.html.erb
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">

    <title>Shipping Information</title>
    <link href="styles/return.css" rel="stylesheet">
    
    
    
</head>

<body>
  
<!-- Credit card form -->
<h2 class="mb-3">Payment Method</h2>

          <div class="my-3">
            <div class="form-check">
              <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required>
              <label class="form-check-label" for="credit">Credit card</label>
            </div>
            <div class="form-check">
              <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="debit">Debit card</label>
            </div>
            <div class="form-check">
              <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="paypal">PayPal</label>
            </div>
          </div>

          <form class="was-validated">
  <div class="col-md-6">
    <label for="validationTextarea">Name on Credit card</label>
    <textarea class="form-control is-invalid" id="validationTextarea" placeholder="Please enter your name " required></textarea>
    <div class="invalid-feedback">
    </div>
  </div>
 <div class="col-md-6">
              <label for="cc-number" class="form-label" name='creditcradnum'>Credit card number</label>
              <input type="number" class="form-control is-inivalid" id="cc-number" placeholder="" required>
              <div class="invalid-feedback">
               
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-expiration" class="form-label">CVV</label>
              <input type="number" class="form-control is-invalid" id="cc-expiration" placeholder="" required>
              <div class="invalid-feedback">
                
              </div>
              
            <div class="col-md-12">
              <label for="cc-expiration" class="form-label">exp date</label>
              <input type="date" class="form-control is-invalid" id="cc-expiration" placeholder="" required>
              <div class="invalid-feedback">
                
              </div>
	 </div>
 <button class="w-100 btn btn-primary btn-lg" type="submit">Add other card</button>
     

<!-- Credit card form -->
  <br>
  <br>
  <br>
  <br>
  
    <article>
        <h2 class="shipprogress">Shipping Information</h2>

        <form action="confirm()" id="shippingForm" name="shippingForm">
            <fieldset>
                <label for="Name">Name:</label>

                
            </fieldset>

            <fieldset>
                <input id="Name" name="Name" type="text">
            
            </fieldset>

            <fieldset>
                <label for="streetAddress1">Street Address:</label>

                <div class="ad2">
                    <label class="ad2" for="streetAddress2">
                    </label>
                </div>
            </fieldset>

            <fieldset>
                <input id="streetAddress1" name="streetAddress1" type="text">
                <input class="streetAddress2" id="streetAddress2" name="streetAddress2" type="text"> <span id="streetAddress_error"></span>
            </fieldset>

            <fieldset>
                <label for="city">City:</label>
            </fieldset>

            <fieldset>
                <input id="city" name="city" type="text"> <span id="city_error"></span>
            </fieldset>

            <fieldset>
                <label for="state">State:</label>
            </fieldset>

            <fieldset>
                <select id="state">
                    <option selected value="0">
                        -
                    </option>

                    <option value="AL">
                        Alabama
                    </option>

                    <option value="AK">
                        Alaska
                    </option>

                    <option value="AZ">
                        Arizona
                    </option>

                    <option value="AR">
                        Arkansas
                    </option>

                    <option value="CA">
                        California
                    </option>

                    <option value="CO">
                        Colorado
                    </option>

                    <option value="CT">
                        Connecticut
                    </option>

                    <option value="DE">
                        Delaware
                    </option>

                    <option value="DC">
                        District Of Columbia
                    </option>

                    <option value="FL">
                        Florida
                    </option>

                    <option value="GA">
                        Georgia
                    </option>

                    <option value="HI">
                        Hawaii
                    </option>

                    <option value="ID">
                        Idaho
                    </option>

                    <option value="IL">
                        Illinois
                    </option>

                    <option value="IN">
                        Indiana
                    </option>

                    <option value="IA">
                        Iowa
                    </option>

                    <option value="KS">
                        Kansas
                    </option>

                    <option value="KY">
                        Kentucky
                    </option>

                    <option value="LA">
                        Louisiana
                    </option>

                    <option value="ME">
                        Maine
                    </option>

                    <option value="MD">
                        Maryland
                    </option>

                    <option value="MA">
                        Massachusetts
                    </option>

                    <option value="MI">
                        Michigan
                    </option>

                    <option value="MN">
                        Minnesota
                    </option>

                    <option value="MS">
                        Mississippi
                    </option>

                    <option value="MO">
                        Missouri
                    </option>

                    <option value="MT">
                        Montana
                    </option>

                    <option value="NE">
                        Nebraska
                    </option>

                    <option value="NV">
                        Nevada
                    </option>

                    <option value="NH">
                        New Hampshire
                    </option>

                    <option value="NJ">
                        New Jersey
                    </option>

                    <option value="NM">
                        New Mexico
                    </option>

                    <option value="NY">
                        New York
                    </option>

                    <option value="NC">
                        North Carolina
                    </option>

                    <option value="ND">
                        North Dakota
                    </option>

                    <option value="OH">
                        Ohio
                    </option>

                    <option value="OK">
                        Oklahoma
                    </option>

                    <option value="OR">
                        Oregon
                    </option>

                    <option value="PA">
                        Pennsylvania
                    </option>

                    <option value="RI">
                        Rhode Island
                    </option>

                    <option value="SC">
                        South Carolina
                    </option>

                    <option value="SD">
                        South Dakota
                    </option>

                    <option value="TN">
                        Tennessee
                    </option>

                    <option value="TX">
                        Texas
                    </option>

                    <option value="UT">
                        Utah
                    </option>

                    <option value="VT">
                        Vermont
                    </option>

                    <option value="VA">
                        Virginia
                    </option>

                    <option value="WA">
                        Washington
                    </option>

                    <option value="WV">
                        West Virginia
                    </option>

                    <option value="WI">
                        Wisconsin
                    </option>

                    <option value="WY">
                        Wyoming
                    </option>
                </select> <span id="state_error"></span>
            </fieldset>

            <fieldset>
                <label for="zipCode">Zip:</label>
            </fieldset>

            <fieldset>
                <input id="zipCode" maxlength="5" name="zipCode" type="text">
                <span id="zipCode_error"></span>
            </fieldset>

            <h2>Contact Information</h2>

            <fieldset>
                <label for="emailAddress1">Email Address:</label>
            </fieldset>

            <fieldset>
                <input id="emailAddress1" name="emailAddress1" type="text">
                <span id="emailAddress1_error"></span>
            </fieldset>

            <fieldset>
                <label for="emailAddress2">Confirm Email:</label>
            </fieldset>

            <fieldset>
                <input id="emailAddress2" name="emailAddress2" type="text">
                <span id="emailAddress2_error"></span>
            </fieldset>

            <fieldset>
                <label for="phoneNumber1">
                    Phone Number:
                </label>
            </fieldset>

            <fieldset>
                
                <input class="phoneNumber1" id="phoneNumber1" maxlength="3" name="phoneNumber1" placeholder=" " type="text">
            </fieldset>

         

        <button class="btn btn-primary btn-lg btn-block" type="submit">
              place Order
            </button>
   </form>
      </div>
    </div>
  </main>
    </article>
<footer></footer>
</body>

</html>

app/views/books/productdetails.html.erb
<h1><%= @book.book_title %></h1>
<%= image_tag 'book2.jpg', class: 'w-100', style: 'max-width: 8rem;' %>
<p>
    Book Description: 
  <%= @book.description %>
</p>
<p>
    Author: 
    <%= @book.book_author %>
</p>
<p>
    Release Date: 
    <%= @book.release_date %>
</p>
<p>
    ID: 
    <%= @book.book_id %>
</p>
<p>
    Price: 
    <%= @book.book_price %>
</p>

<p>
<%= link_to 'Back', books_path, class: 'btn btn-primary' %>
<%= link_to 'Buy', myorder_path, class: 'btn btn-primary' %>

<%= bootstrap_form_with model: @review, method: :patch, url: review_path, method: :post, local: true do |f| %>
    <%= f.text_field :review %>
    <%= link_to 'Submit', reviewresult_path, class: 'btn btn-primary' %>
   
<% end %>

app/views/books/productlisting.html.erb
<%= link_to 'Home', dashboard_path(@dashboard), class: 'btn btn-primary' %> 
<h1>Book Items</h1>
<%= render "books/form" %>
<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th> </th>
      <th>Book ID</th>
      <th>Release Date</th>
      <th>Author</th>
      <th>Price</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        
        <td><%= book.book_title %></td>
        <td><%= image_tag 'book1.jpg', class: 'w-100 rounded-circle shadow-lg d-block mx-auto', style: 'max-width: 5rem;' %></td> 
        <td><%= book.book_id %></td>
        <td><%= book.release_date %></td>
        <td><%= book.book_author %></td>
        <td><%= book.book_price %></td>
        <td><%= link_to "click here", book_path(book) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/reviewresult.html.erb
<h1>My Orders</h1>
<p>
Thank You for submitting your review, We will let you know if you are eligible for the bonus coupon after receiving all the reviews.
</p>